### ISSUE TITLE
[BUG] Segfault when including empty Rego file

### ISSUE THREAD

**Issue by Octogonapus** [fugue/regula#357]
**Describe the bug**
A segfault occurs when you run Regula while including an empty Rego file.

**How you're running Regula**
Regula CLI 2.9.1, build b46cb87, built with OPA v0.43.0

**Operating System**
5.19.6-200.fc36.x86_64

**Steps to reproduce**
```sh
touch empty.rego
touch foo.tf
regula run -i empty.rego foo.tf
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0xc42257]

goroutine 1 [running]:
github.com/open-policy-agent/opa/rego.preparedQuery.Modules(...)
	github.com/open-policy-agent/opa@v0.43.0/rego/rego.go:280
github.com/fugue/regula/v2/pkg/rego.RunRules({0x12f9bc0, 0xc000130638}, 0xc000d1fd40)
	github.com/fugue/regula/v2/pkg/rego/runrules.go:59 +0x537
github.com/fugue/regula/v2/cmd.NewRunCommand.func1(0xc000148f00, {0xc0003d8cf0, 0x1, 0x3})
	github.com/fugue/regula/v2/cmd/run.go:149 +0x8e5
github.com/spf13/cobra.(*Command).execute(0xc000148f00, {0xc0003d8cc0, 0x3, 0x3})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x1a59140)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/fugue/regula/v2/cmd.Execute()
	github.com/fugue/regula/v2/cmd/root.go:47 +0x25
main.main()
	github.com/fugue/regula/v2/main.go:22 +0x17
```

**Comment by jaspervdj-luminal** [comment]
Should be fixed in v2.9.2, please reopen if this still occurs.
