### ISSUE TITLE
[BUG] panic scanning terraform source

### ISSUE THREAD

**Issue by szesch** [fugue/regula#397]
**Describe the bug**
I'm seeing an error `panic: can't use ElementIterator on null value` when scanning terraform source. I've narrowed this down to referencing `data` sources. They occur within a `for_each` but I'm not sure if that contributes to the error or not.

```
goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.ElementIterator({{{0x1302910?, 0xc00c434ef0?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1121 +0xc5
github.com/zclconf/go-cty/cty.Value.AsValueMap({{{0x1302910?, 0xc00c434ef0?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1324 +0xa5
github.com/snyk/policy-engine/pkg/hcl_interpreter.Term.Evaluate({0x0, 0xc00af49b60, 0xc00af49b90, 0x0, 0xc001a9d5c0}, 0xc00ef23f80)
        /home/runner/go/pkg/mod/github.com/snyk/policy-engine@v0.17.0/pkg/hcl_interpreter/term.go:202 +0x2c5
github.com/snyk/policy-engine/pkg/hcl_interpreter.(*Evaluation).evaluate(0xc007e6b840)
        /home/runner/go/pkg/mod/github.com/snyk/policy-engine@v0.17.0/pkg/hcl_interpreter/hcl_interpreter.go:251 +0x5c9
github.com/snyk/policy-engine/pkg/hcl_interpreter.EvaluateAnalysis(0xc007e6b7c0)
        /home/runner/go/pkg/mod/github.com/snyk/policy-engine@v0.17.0/pkg/hcl_interpreter/hcl_interpreter.go:199 +0x1cc
github.com/fugue/regula/v3/pkg/loader.newHclConfiguration(0xc002999860)
        /home/runner/work/regula/regula/pkg/loader/tf.go:105 +0x2a
github.com/fugue/regula/v3/pkg/loader.(*TfDetector).DetectDirectory(0xc00004a240?, {0x13039e0, 0xc000541d80}, {0x20?, 0xf8?, {0x0?, 0x4?, 0x0?}})
        /home/runner/work/regula/regula/pkg/loader/tf.go:95 +0x265
github.com/fugue/regula/v3/pkg/loader.(*directory).DetectType(0xc0001389a0?, {0x12fd018?, 0x1bb64b8?}, {0x59?, 0x40?, {0x0?, 0x4?, 0xc0005381e0?}})
        /home/runner/work/regula/regula/pkg/loader/input.go:32 +0x39
github.com/fugue/regula/v3/pkg/loader.(*AutoDetector).DetectDirectory(0x2f?, {0x13039e0, 0xc000541d80}, {0xc0?, 0x77?, {0x0?, 0xc000ed4600?, 0xc01129f8e0?}})
        /home/runner/work/regula/regula/pkg/loader/auto.go:26 +0xf8
github.com/fugue/regula/v3/pkg/loader.(*directory).DetectType(0xf5e000?, {0x12fcfa0?, 0xc00012ceb8?}, {0x13?, 0x0?, {0x0?, 0x7f267f415698?, 0xc000538690?}})
        /home/runner/work/regula/regula/pkg/loader/input.go:32 +0x39
github.com/fugue/regula/v3/pkg/loader.LocalConfigurationLoader.func1.1({0x7f267f415810, 0xc000541d80})
        /home/runner/work/regula/regula/pkg/loader/loadpaths.go:68 +0xd7
github.com/fugue/regula/v3/pkg/loader.(*directory).Walk(0x7f267f415810?, 0xc00023f260)
        /home/runner/work/regula/regula/pkg/loader/input.go:49 +0x7f
github.com/fugue/regula/v3/pkg/loader.(*directory).Walk(0x108bbf0?, 0xc00023f260)
        /home/runner/work/regula/regula/pkg/loader/input.go:57 +0xb3
github.com/fugue/regula/v3/pkg/loader.LocalConfigurationLoader.func1()
        /home/runner/work/regula/regula/pkg/loader/loadpaths.go:138 +0x612
github.com/fugue/regula/v3/cmd.NewRunCommand.func1(0xc0002aec00, {0xc00038e2e0, 0x0, 0x1})
        /home/runner/work/regula/regula/cmd/run.go:145 +0x7f7
github.com/spf13/cobra.(*Command).execute(0xc0002aec00, {0xc00038e2c0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1b508a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/fugue/regula/v3/cmd.Execute()
        /home/runner/work/regula/regula/cmd/root.go:47 +0x25
main.main()
        /home/runner/work/regula/regula/main.go:22 +0x17

```

**How you're running Regula**
I'm using Regula v3.1.0 as a CLI tool and my Terraform source code as an input:

**Operating System**
Ubuntu 22.04

**Steps to reproduce**
1. `regula run -v` this should produce the error
2. Comment out the two lines under the comment in `aws_lb_target_group_attachment` and rerun. It should work

**IaC Configuration**
```
data "aws_msk_broker_nodes" "msk_nodes" {
  cluster_arn = "cluster-arn"
}

resource "aws_lb" "msk" {
  name               = "msk-private-link-ingress"
  load_balancer_type = "network"
  internal           = true
  subnets            =  ["subnet-000000", "subnet-111111", "subnet-222222"]
}

resource "aws_lb_target_group" "msk_nlb_target_groups" {
  count       = 3
  name        = "msk-dynamic-broker${count.index}"
  port        = 1234
  protocol    = "TCP"
  target_type = "ip"
  vpc_id      = "vpc-0123456789"
}

resource "aws_lb_target_group_attachment" "msk_tgr_attachment" {
  for_each = {
    for i, k in aws_lb_target_group.msk_nlb_target_groups :
    i => {
      target_group = aws_lb_target_group.msk_nlb_target_groups[i]

      # These two lines cause the error
      instance_ip  = data.aws_msk_broker_nodes.msk_nodes.node_info_list[i].client_vpc_ip_address
      broker_id    = data.aws_msk_broker_nodes.msk_nodes.node_info_list[i].broker_id
    }
  }
  target_group_arn = each.value.target_group.arn
  target_id        = each.value.instance_ip
} 
```

**Comment by jaspervdj-luminal** [comment]
This should be fixed in regula `v3.2.1`.
